config/routes.rb
Rails.application.routes.draw do
  devise_for :members, :controllers => { :registrations => "members/registrations" }
  resources :members
  resources :members
  resources :seasons

  get 'admin' => 'admin#index'

  root 'seasons#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  has_many :memberships
  has_many :seasons, through: :memberships

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :address, presence: true, uniqueness: true
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member
  belongs_to :season
  belongs_to :month

  validates :member_id, uniqueness: { scope: :season_id, allow_nil: true }
  validates :season_id, presence: true
  validates :month_id, presence: true, uniqueness: { scope: :season_id }

  default_scope { includes(:month).order('months.order') }
end

app/models/month.rb
class Month < ActiveRecord::Base

  NAMES = Date::MONTHNAMES.compact

  validates :name, presence: true, uniqueness: true, inclusion: { in: NAMES }
  validates :order, presence: true, uniqueness: true, numericality: { less_than: 12, greater_than: -1 }

  default_scope { order(:order) }

  def self.ensure_12_months
    if Month.count < 12
      12.times do |i|
        Month.find_or_create_by order: i, name: NAMES[i]
      end
    end
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :memberships, validate: true
  has_many :members, through: :memberships
  accepts_nested_attributes_for :memberships

  validates :name, presence: true, uniqueness: true
  validates :beginning_date, presence: true, uniqueness: true
  validates :ending_date, presence: true, uniqueness: true

  validate :validate_sane_dates

  def create_unfilled_memberships
    Month.ensure_12_months

    Month.all.each do |month|
      actual_membership = self.memberships.find_by(month: month)
      if actual_membership.nil?
        Membership.create! season: self, month: month
      end
    end
  end

  private

  def validate_sane_dates
    if beginning_date.present? && ending_date.present?
      unless beginning_date < ending_date
        errors.add(:ending_date, "must come after beginning date")
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :address)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email, :address, :password, :password_confirmation)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  before_action :enforce_no_duplicate_members, only: [:update]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season.create_unfilled_memberships
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
    @season.create_unfilled_memberships
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :beginning_date, :ending_date, memberships_attributes: [:id, :month_id, :member_id])
    end

    def enforce_no_duplicate_members
      membership_hashes = season_params["memberships_attributes"].try(:values)
      if membership_hashes.present?
        membership_ids = membership_hashes.map{|membership_hash| membership_hash['member_id']}
        membership_ids.reject!{ |membership_id| membership_id.blank? }

        if membership_ids != membership_ids.uniq
          flash[:alert] = "There are duplicate members in this season"
          render :edit
        end
      end
    end
end

app/views/admin/index.html.haml
= link_to 'Seasons', seasons_path
= link_to 'Members', members_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cdclub
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice.alert.alert-info= notice
    %p.alert.alert.alert-info= alert

    = yield

app/views/members/_form.html.haml
= form_for(@member) do |f|
  - if @member.errors.any?
    #error_explanation
      %h2
        = pluralize(@member.errors.count, "error")
        prohibited this member from being saved:
      %ul
        - @member.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :address
    %br/
    = f.text_area :address
  .actions
    = f.submit

app/views/members/edit.html.haml
%h1 Editing Member
= render 'form'
= link_to 'Show', @member
|
= link_to 'Back', members_path

app/views/members/index.html.haml
%p#notice= notice
%h1 Listing Members
%table
  %thead
    %tr
      %th Name
      %th Email
      %th Address
      %th{colspan: "3"}
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.name, member
        %td= member.email
        %td= member.address
        %td= link_to 'Edit', edit_member_path(member)
        %td= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New Member
= render 'form'
= link_to 'Back', members_path

app/views/members/show.html.haml
%p
  %strong Name:
  = @member.name
%p
  %strong Email:
  = @member.email
%p
  %strong Address:
  = @member.address
= link_to 'Alter Member', edit_member_path(@member)
|
= link_to 'Back', members_path

app/views/seasons/_form.html.haml
= form_for(@season) do |f|
  - if @season.errors.any?
    #error_explanation
      %h2
        = pluralize(@season.errors.count, "error")
        prohibited this season from being saved:
      %ul
        - @season.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :beginning_date
    %br/
    = f.date_select :beginning_date
  .field
    = f.label :ending_date
    %br/
    = f.date_select :ending_date
  = @season.name
  Members List
  %table
    = f.fields_for :memberships do |mf|
      %tr{id: "#{mf.object.month.name.downcase}_membership"}
        %td= mf.label :member_id, mf.object.month.name
        %td= mf.collection_select(:member_id, Member.all, :id, :name, { include_blank: true } )
  .actions
    = f.submit

app/views/seasons/edit.html.haml
%h1 Editing Season
= render 'form'
= link_to 'Show', @season
|
= link_to 'Back', seasons_path

app/views/seasons/index.html.haml
%p#notice= notice
%h1 Listing Seasons
%table
  %thead
    %tr
      %th Name
      %th Beginning date
      %th Ending date
      %th{colspan: "2"}
  %tbody
    - @seasons.each do |season|
      %tr
        %td= link_to season.name, season
        %td= season.beginning_date
        %td= season.ending_date
        %td= link_to 'Edit', edit_season_path(season)
        %td= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Season', new_season_path

app/views/seasons/membership.html.haml
= form_for @season do |f|
  = @season.name
  Members List
  %ul
    = f.fields_for :memberships do |memberships_form|
      %li
        = memberships_form.select(:month, options_for_select((1..12).map {|m| month_name = Month::NAMES[m - 1] [month_name, month_name]}))
        = memberships_form.collection_select(:member_id, Member.all, :id, :name)

app/views/seasons/new.html.haml
%h1 New Season
= render 'form'
= link_to 'Back', seasons_path

app/views/seasons/show.html.haml
/ %p#notice= notice
%p
  %strong Name:
  = @season.name
%p
  %strong Beginning date:
  = @season.beginning_date
%p
  %strong Ending date:
  = @season.ending_date
%div
  %table
    - @season.memberships.each do |membership|
      %tr{id: "#{membership.month.name.downcase}_membership"}
        %td= membership.month.name
        %td= membership.member.try(:name)

= link_to 'Alter Season', edit_season_path(@season)
|
= link_to 'Back', seasons_path